# Generated by Django 3.2.8 on 2021-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='https://res.cloudinary.com/oti/image/upload/v1634906359/avatar_dzg8jx.png', upload_to='avatars/'),
        ),
    ]
